service: sls-simple-pipeline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: us-east-1
  role: arn:aws:iam::#{AWS::AccountId}:role/serverless-poc-lambda

# you can define service wide environment variables here
environment:
    TWITTER_ACCESS_TOKEN: '1234abcd'

custom:
  stages:
  - dev
  - qa
  - prod
  value:
    dev: Hello
    qa: Bye
  deploymentSettings:
    codeDeployRole: arn:aws:iam::788601987176:role/lambda-sam-pipeline-stack-CodeDeployServiceRole-1UW4T6QD1972X
  #   stages:
  #     - dev

package:
  exclude:
    - artifacts/**

functions:
  hello:
    handler: handler.hello
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live
    events:
      - http: 
          path: hello
          method: GET

plugins:
- serverless-stage-manager
- serverless-pseudo-parameters
- serverless-plugin-canary-deployments